### PR TITLE
Tweaks to powershell script for VS2010 and VS2015

### PR DESCRIPTION
**Pull request by matthill**
I was playing with this script for a couple hours.  It's really great.  Here's some changes I applied to my environment, in case it's useful.

### CODE REVIEW

**Comment by matthill** [comment]
Two other things I noted that I had to do on my system:

Set-ExecutionPolicy RemoteSigned
  choose "Y" to allow

Make sure "MSBuild.exe" is on the system path

**Comment by matthill** [comment]
I also just added a link to the Windows compilation instructions here:
https://github.com/openalpr/openalpr/wiki/Compilation-instructions-(Windows)

**Comment by peters** [comment]
@matthill I've made some additional changes.

**Comment by peters** [comment]
The build instructions url should point to a tag version. I'm planning on creating a new tag for the build script every time you make a release so i don't have to worry about breaking older builds :)

**Pull request merged**
